replicaCount: 1

image:
  repository: REGISTRY_URL
  tag: BUILD_ID
  pullPolicy: Always
  registrySecret: REGISTRY_SECRET_ID

nameOverride: #SERVICE_NAME#
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  internalport: CONTAINER_PORT

updateStrategy:
  rollingUpdate:
    maxUnavailable: 0
  type: RollingUpdate

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  paths:
    path: /RELEASE_NAME


context: CONTEXT_PATH

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
    cpu: 300m
    memory: 2Gi
   requests:
    cpu: 250m
    memory: 1500Mi
  

nodeSelector: {}

tolerations: []

affinity: {}
